name: Build

on:
  push

jobs:
  build:
    runs-on: ubuntu:20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install dependencies [1/2]
        run: apt install -y libime
      
      - name: Install dependencies [2/2]
        run: pip install opencc pypinyin
      
      - name: Test for builds
        run: bash tests/test.sh